order-management-fe/package.json, order-management-fe/src/App.test.js, order-management-fe/src/components/AuthContainer/index.jsx, order-management-fe/src/components/CustomFormGroup/index.jsx, order-management-fe/src/tests/modules/login.test.js, order-management-fe/src/tests/utils/dummy.login.js, order-management-fe/src/validations/auth.js
=> feat: login page unit test cases

order-management-be/package.json, order-management-be/src/api/repositories/owner.repository.js, order-management-be/src/config/express.js, order-management-be/swagger.json
1. Swagger documentation added for owner apis
=> feat: swagger documentation added

order-management-be/.eslintrc.cjs, order-management-be/package.json, order-management-fe/.eslintrc.js, order-management-fe/package.json
1. lint configuration for backend
2. lint configuration for frontend
=> feat: eslint-configuration

order-management-fe/src/components/CustomFormGroup/index.jsx, order-management-fe/src/components/Modal/index.jsx, order-management-fe/src/components/Sidebar/index.jsx, order-management-fe/src/pages/Hotels/hotelSchema.js, order-management-fe/src/pages/Hotels/index.jsx, order-management-fe/src/routes/index.jsx
Added hotel tab and created add new hotel modal.
=> designed ui for create hotel modal.

order-management-be/src/api/models/user.model.js, order-management-be/src/api/services/email.service.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/templates/inviteManager.html, order-management-be/src/api/tests/modules/hotel.test.js, order-management-be/src/api/tests/utils/dummy.hotel.js, order-management-be/src/api/utils/common.js, order-management-be/src/api/validations/hotel.validation.js, order-management-be/swagger.json
1. All instances of admin updated to manager
2. test cases updated
=> RO-001 - Update Admin to Manager Backend

order-management-fe/src/components/CustomButton/index.jsx, order-management-fe/src/components/Modal/index.jsx, order-management-fe/src/pages/Invites/index.jsx
1. All instances of admin updated to Manager
2. Test cases updated
=> RO-002 - FE: Update Admin to Manager

order-management-be/swagger.json
1. Swagger documentation corrected
=> RO-012 - Auth api's swagger documentation

order-management-be/src/api/routes/user.routes.js, order-management-be/swagger.json, order-management-fe/src/pages/Invites/index.jsx, order-management-fe/src/services/invite.service.js
1. Api documentation updated for invite apis
=> RO-013: API documentation for Invite api updated

order-management-be/src/api/models/hotel.model.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/tests/utils/dummy.hotel.js, order-management-be/src/api/validations/hotel.validation.js, order-management-be/swagger.json
1. Swagger documentation for hotel apis updated
2. Refactoring done
=> RO-014: Swagger doc for Hotel apis

order-management-be/.eslintrc.cjs, order-management-be/src/api/controllers/user.controllers.js, order-management-be/src/api/repositories/invite.repository.js, order-management-be/src/api/repositories/user.repository.js, order-management-be/src/api/services/email.service.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/validations/user.validations.js, order-management-be/src/config/database.js, order-management-be/src/config/logger.js, order-management-be/src/index.js, package.json
1. Winston Logger added
2. Logger added to auth apis
=> RO-020 - Add Logger to Auth apis

order-management-be/.eslintrc.cjs, order-management-be/src/api/controllers/user.controllers.js, order-management-be/src/api/middlewares/auth.js, order-management-be/src/api/middlewares/roleAuth.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/tests/modules/auth.test.js, order-management-be/src/api/tests/modules/hotel.test.js, order-management-be/src/api/tests/modules/invite.test.js, order-management-be/src/api/tests/utils/dummy.invite.js, order-management-be/src/config/express.js, order-management-fe/.eslintrc.js
1. Logger added for auth middleware
2. Logger added for roleAuth middleware
3. Logger added for invite apis
4. es-lint rule updated
5. lint errors fixed
=> RO-21 - Logs added for Invite Apis

order-management-be/src/api/controllers/hotel.controller.js, order-management-be/src/api/repositories/hotel.repository.js, order-management-be/src/api/repositories/hotelUserRelation.repository.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/validations/hotel.validation.js
1. Loggers added to Hotel apis
=> RO-22 - Hotel apis logs

order-management-fe/src/tests/modules/pages/login.test.js, order-management-fe/src/tests/modules/pages/signup.test.js
1. unwanted console removed from frontend
=> RO-23 - Frontend logs removed

.gitignore, order-management-be/jest.config.js, order-management-be/package.json, order-management-be/sonar-project.properties, order-management-fe/package.json, order-management-fe/sonar-project.properties
1. sonar qube implemented in frontend
=> RO-18 : FE: SonarQube Integration

order-management-be/src/api/controllers/manager.controller.js, order-management-be/src/api/models/associations.js, order-management-be/src/api/models/invite.model.js, order-management-be/src/api/repositories/hotelUserRelation.repository.js, order-management-be/src/api/routes/index.js, order-management-be/src/api/routes/manager.routes.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/services/manager.service.js, order-management-be/src/api/services/user.service.js
=> RO-37: List managers api

order-management-be/src/api/controllers/manager.controller.js, order-management-be/src/api/models/invite.model.js, order-management-be/src/api/repositories/hotelUserRelation.repository.js, order-management-be/src/api/repositories/user.repository.js, order-management-be/src/api/routes/index.js, order-management-be/src/api/routes/manager.routes.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/services/manager.service.js, order-management-be/src/api/services/user.service.js
1. Remove managers api done
2. Lint fixes done
=> R0-39: Remove user api

order-management-be/src/api/services/hotel.service.js
1. Assigned managers added in list apis
=> RO-40: Get hotels apis bug fix

order-management-be/src/api/controllers/manager.controller.js, order-management-be/src/api/routes/manager.routes.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/services/manager.service.js, order-management-be/src/api/validations/manager.validation.js
1. Get assignable managers done
=> RO-41: Get assignable managers api

order-management-be/src/api/controllers/table.controller.js, order-management-be/src/api/models/associations.js, order-management-be/src/api/models/table.model.js, order-management-be/src/api/repositories/table.repository.js, order-management-be/src/api/routes/index.js, order-management-be/src/api/routes/tables.routes.js, order-management-be/src/api/services/table.service.js, order-management-be/src/api/utils/common.js, order-management-be/src/api/validations/table.validation.js, order-management-be/src/config/database.js
1. Table model created
2. Create table api done
=> RO-42t: Create hotel api done

order-management-be/src/api/controllers/table.controller.js, order-management-be/src/api/repositories/table.repository.js, order-management-be/src/api/routes/tables.routes.js, order-management-be/src/api/services/table.service.js, order-management-be/src/api/validations/table.validation.js
1. List tables api done
2. Delete table api done
=> RO-43: List and delete table apis

order-management-be/.husky/pre-push, order-management-be/src/api/controllers/menu.controller.js, order-management-be/src/api/repositories/menu.repository.js, order-management-be/src/api/routes/menu.routes.js, order-management-be/src/api/services/menu.service.js, order-management-be/src/api/validations/menu.validation.js
1. Create menu item done
2. updated menu item done
3. remove menu item done
=> RO-50: Menu Operations

order-management-be/src/api/models/associations.js, order-management-be/src/api/models/preferences.model.js, order-management-be/src/api/repositories/preferences.repository.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/utils/common.js, order-management-be/src/api/validations/user.validations.js, order-management-be/src/config/database.js, order-management-fe/src/assets/styles/settings.css, order-management-fe/src/components/CustomFormGroup/index.jsx, order-management-fe/src/components/Navbar/index.jsx, order-management-fe/src/pages/Hotels/index.jsx, order-management-fe/src/pages/Settings/index.jsx, order-management-fe/src/routes/index.jsx, order-management-fe/src/services/auth.service.js, order-management-fe/src/store/sagas/auth.saga.js, order-management-fe/src/store/sagas/hotel.saga.js, order-management-fe/src/store/slice/auth.slice.js, order-management-fe/src/store/slice/hotel.slice.js, order-management-fe/src/store/types/auth.js, order-management-fe/src/validations/auth.js
1. BE: update user api done
2. FE: Settings tab done
3. FE: Update user model done
=> RO-53: settings tab

order-management-be/src/api/repositories/category.repository.js, order-management-be/src/api/repositories/user.repository.js, order-management-be/src/api/services/menu.service.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/validations/menu.validation.js, order-management-fe/src/components/AuthContainer/index.jsx, order-management-fe/src/components/CustomFormGroup/index.jsx, order-management-fe/src/components/Modal/index.jsx, order-management-fe/src/components/Navbar/index.jsx, order-management-fe/src/components/Table/index.jsx, order-management-fe/src/pages/Menu/index.jsx, order-management-fe/src/services/menu.service.js, order-management-fe/src/store/reducers/index.js, order-management-fe/src/store/sagas/index.js, order-management-fe/src/store/sagas/manager.saga.js, order-management-fe/src/store/sagas/menu.saga.js, order-management-fe/src/store/slice/index.js, order-management-fe/src/store/slice/menu.slice.js, order-management-fe/src/store/types/menu.js, order-management-fe/src/validations/menu.js
1. Modal added for create category
2. Api to add category in Bulk added
3. Menu tab added
=> RO-55: create category

order-management-be/src/api/controllers/menu.controller.js, order-management-be/src/api/routes/menu.routes.js, order-management-be/src/api/services/menu.service.js, order-management-fe/src/assets/styles/formGroup.css, order-management-fe/src/components/CustomFormGroup/index.jsx, order-management-fe/src/pages/Menu/index.jsx, order-management-fe/src/services/menu.service.js, order-management-fe/src/store/sagas/menu.saga.js, order-management-fe/src/store/slice/menu.slice.js, order-management-fe/src/store/types/menu.js, order-management-fe/src/validations/menu.js
1. Get category integrations done
2. Delete category integration done
3. Update category integration done
4. Update category api modified
5. Delete categories api modified
6. Get categories api modified
=> RO-56: Category operations

order-management-be/src/api/controllers/menu.controller.js, order-management-be/src/api/repositories/menu.repository.js, order-management-be/src/api/routes/menu.routes.js, order-management-be/src/api/services/menu.service.js, order-management-be/src/api/validations/menu.validation.js, order-management-fe/src/components/Table/index.jsx, order-management-fe/src/pages/Menu/index.jsx, order-management-fe/src/services/menu.service.js, order-management-fe/src/store/sagas/menu.saga.js, order-management-fe/src/store/slice/menu.slice.js, order-management-fe/src/store/types/menu.js, order-management-fe/src/validations/menu.js
1. Add menu done
2. remove menu items
3. list menu items
4. update menu items
5. Add category done
6. Remove category done
7. List category done
8. update category done
=> RO-57: Menu Operations

order-management-be/src/api/models/menu.model.js, order-management-be/src/api/models/table.model.js, order-management-be/src/api/routes/menu.routes.js, order-management-be/src/api/validations/menu.validation.js, order-management-fe/src/components/Navbar/index.jsx, order-management-fe/src/components/Sidebar/index.jsx, order-management-fe/src/config/env.js, order-management-fe/src/pages/Menu/index.jsx, order-management-fe/src/pages/Tables/index.jsx, order-management-fe/src/store/sagas/auth.saga.js, order-management-fe/src/store/slice/menu.slice.js, order-management-fe/src/store/slice/table.slice.js, order-management-fe/src/utils/auth.js, order-management-fe/src/utils/constants.js, order-management-fe/src/utils/hotel.js
1. Status added for Table
2. Status added for Menu
=> RO-59: Add menu and table status

order-management-be/package.json, order-management-be/src/api/controllers/order.controller.js, order-management-be/src/api/models/associations.js, order-management-be/src/api/models/customer.modal.js, order-management-be/src/api/models/table.model.js, order-management-be/src/api/repositories/customer.repository.js, order-management-be/src/api/repositories/table.repository.js, order-management-be/src/api/routes/index.js, order-management-be/src/api/routes/order.routes.js, order-management-be/src/api/services/order.service.js, order-management-be/src/api/services/table.service.js, order-management-be/src/api/utils/common.js, order-management-be/src/api/validations/order.validation.js, order-management-be/src/config/database.js, order-management-be/src/config/logger.js, order-management-fe/src/components/MenuCard/index.jsx, order-management-fe/src/pages/OrderPlacement/index.jsx, order-management-fe/src/pages/Tables/index.jsx, order-management-fe/src/services/orderPlacement.service.js, order-management-fe/src/store/sagas/index.js, order-management-fe/src/store/sagas/orderPlacement.saga.js, order-management-fe/src/store/slice/orderPlacement.slice.js, order-management-fe/src/store/types/index.js, order-management-fe/src/store/types/orderPlacement.js, order-management-fe/src/store/types/place.js, order-management-fe/src/validations/orderPlacement.js
1. Customer registeration done
2. Get Table association formed
3. customer registeration api integrated
=> RO-61: Customer registeration

order-management-be/.husky/pre-commit, order-management-be/.husky/pre-push, order-management-be/src/api/controllers/hotel.controller.js, order-management-be/src/api/controllers/order.controller.js, order-management-be/src/api/models/associations.js, order-management-be/src/api/models/order.model.js, order-management-be/src/api/routes/hotel.routes.js, order-management-be/src/api/routes/order.routes.js, order-management-be/src/api/services/hotel.service.js, order-management-be/src/api/services/order.service.js, order-management-be/src/api/utils/common.js, order-management-be/src/config/database.js, order-management-fe/.husky/pre-commit, order-management-fe/src/pages/OrderPlacement/index.jsx, order-management-fe/src/services/hotel.service.js, order-management-fe/src/services/orderPlacement.service.js, order-management-fe/src/store/reducers/index.js, order-management-fe/src/store/sagas/hotel.saga.js, order-management-fe/src/store/sagas/orderPlacement.saga.js, order-management-fe/src/store/slice/hotel.slice.js, order-management-fe/src/store/slice/orderPlacement.slice.js, order-management-fe/src/store/types/hotel.js, order-management-fe/src/store/types/orderPlacement.js
1. menu card details api updated
2. menu card api integration refactored
=> RO-62: Refactor menu card details

order-management-be/src/api/controllers/order.controller.js, order-management-be/src/api/models/order.model.js, order-management-be/src/api/repositories/order.repository.js, order-management-be/src/api/routes/order.routes.js, order-management-be/src/api/services/order.service.js, order-management-be/src/api/services/user.service.js, order-management-be/src/api/validations/order.validation.js, order-management-fe/src/api/apiClient.js, order-management-fe/src/assets/styles/menuCard.css, order-management-fe/src/components/MenuCard/index.jsx, order-management-fe/src/pages/OrderPlacement/index.jsx, order-management-fe/src/pages/Tables/index.jsx, order-management-fe/src/services/orderPlacement.service.js, order-management-fe/src/store/sagas/orderPlacement.saga.js, order-management-fe/src/store/slice/orderPlacement.slice.js, order-management-fe/src/store/types/orderPlacement.js, order-management-fe/src/utils/constants.js
1. BE order placement flow
2. FE order placement flow
=> RO-63: Order placement flow

order-management-be/src/api/controllers/order.controller.js, order-management-be/src/api/repositories/customer.repository.js, order-management-be/src/api/repositories/order.repository.js, order-management-be/src/api/routes/order.routes.js, order-management-be/src/api/services/order.service.js, order-management-be/src/api/validations/order.validation.js, order-management-fe/src/assets/styles/settings.css, order-management-fe/src/pages/OrderPlacement/index.jsx, order-management-fe/src/pages/Settings/index.jsx
1. payment feedback flow done
2. FE-minor frontend fixes
3. lint fixes
=> Ro 64/payment feedback flow
